name: Download XML File

on:
  schedule:
    - cron: '0 * * * *' # This cron expression runs the job every 60 minutes

jobs:
  download-xml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download XML file
      run: |
        mkdir -p daily
        curl -o daily/file.xml https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRFZxYUdjU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US%3Aen

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add daily/file.xml
        git commit -m "Update XML file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
